services:
  - type: web
    name: oxibot-frontend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8080
    workingDir: fronted
    autoDeploy: true

  - type: web
    name: oxibot-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    workingDir: backend
    autoDeploy: true
